### ISSUE TITLE
return or control

### ISSUE THREAD

**Issue by davidsu** [jasonrudolph/ControlEscape.spoon#11]
Hi, awesome spoon you have here, thanks for it!!!

how would one go about doing the same thing for controlReturn instead?

**Comment by jasonrudolph** [comment]
> awesome spoon you have here, thanks for it!!!

👋 @davidsu: Glad you like it. :-) 

> how would one go about doing the same thing for controlReturn instead?

I haven't tried that, but I'd probably start by finding all the references to `escape` in [`init.lua`](https://github.com/jasonrudolph/ControlEscape.spoon/blob/cc5749931afe61c299ac8371230ec77a870b775a/init.lua) and changing them to refer to `return` instead.

https://github.com/jasonrudolph/keyboard/pull/33 might also provide some inspiration. I haven't tried out that pull request, but it might be a useful reference for you.

I hope that helps.

**Comment by davidsu** [comment]
Thanks a lot. I just read the code on that pr, looks promising.
About modifying the code in this spoon, i tried that but got stuck
somewhere, this code works well for modifier keys(ctrl OR escape), to make
it the other way around is not that straight forward(I need return OR ctrl,
the parallel would be escape OR ctrl).

The little success that I had(and again, not good enough) made the return
very clunky(slow to respond). I'll try to play with that pr, im sure that
with that reference i can get the functionality that i want, about
responsiveness, i'm in doubt that hamerspoon can give me what i need.

Thanks a lot for your help.
