### ISSUE TITLE
Sometimes escape doesnt work in vim

### ISSUE THREAD

**Issue by GZLiew** [jasonrudolph/ControlEscape.spoon#13]
I have a weird problem when I go into insert mode in vim and want to exit back to normal mode with capslock as escape it doesnt always work very well and I have to press caps lock multiple times for the escape key to register

https://user-images.githubusercontent.com/43195293/144963186-cbedd854-c38d-4f49-813c-37b40eae6e60.mov

**Comment by jasonrudolph** [comment]
> I have a weird problem when I go into insert mode in vim and want to exit back to normal mode with capslock as escape it doesnt always work very well and I have to press caps lock multiple times for the escape key to register

👋 @GZLiew: Thanks for the bug report and the video. Sorry you're having this issue. I'm not sure what's causing this, but if you're able to figure it out, I'd definitely welcome a pull request to make things more robust.
