### ISSUE TITLE
Does not map caps lock to control or escape

### ISSUE THREAD

**Issue by sai29** [jasonrudolph/ControlEscape.spoon#2]
This is the output from my hammerspoon console

`2017-06-26 11:46:42: -- Lazy extension loading enabled`
`2017-06-26 11:46:42: -- Loading ~/.hammerspoon/init.lua`
`2017-06-26 11:46:42: -- Loading Spoon: ControlEscape`
`2017-06-26 11:46:42: -- Loading extension: timer`
`2017-06-26 11:46:42: -- Loading extension: eventtap`
`2017-06-26 11:46:42: -- Done.`

**Comment by jasonrudolph** [comment]
:wave: @sai29: I have a couple questions for you to help us debug this issue:

1. When you quickly tap-and-release the physical <kbd>control</kbd>key, does it act like <kbd>escape</kbd>?
2. Have you remapped [<kbd>caps lock</kbd> to <kbd>control</kbd> in System Preferences](https://github.com/jasonrudolph/ControlEscape.spoon/tree/1f66deee41aaf0f0c0e38aabc0d66977ec8ffedc#optional-youre-just-a-few-seconds-away-from-a-more-useful-caps-lock-key) as shown in the screenshot below?

![screenshot](https://user-images.githubusercontent.com/2988/27111039-7f620442-507b-11e7-9bcf-93d46e14af13.png)

**Comment by sai29** [comment]
@jasonrudolph That fixed it. Thanks!
