### ISSUE TITLE
Installation process fails when Hammerspoon is already installed

### ISSUE THREAD

**Issue by spring-haru** [jasonrudolph/ControlEscape.spoon#3]
Hi,

I attempted to install ControlEscape.spoon, following the steps explained in the site. Then, the process generates an error at the stage of `script/setup` with the following error message in Terminal:

```
brew bundle can't satisfy your Brewfile's dependencies.
Satisfy missing dependencies with `brew bundle install`.
Using caskroom/cask
==> Satisfying dependencies
==> Downloading https://github.com/Hammerspoon/hammerspoon/releases/download/0.9.55/Hammerspoon-0.9.55.zip
Already downloaded: /Users/Tetsu/Library/Caches/Homebrew/Cask/hammerspoon--0.9.55.zip
==> Verifying checksum for Cask hammerspoon
==> Installing Cask hammerspoon
Error: It seems there is already an App at '/Applications/Hammerspoon.app'.
Error: Install incomplete.
Installing hammerspoon has failed!
Homebrew Bundle failed! 1 Brewfile dependencies failed to install.

```

Entering `hs.loadSpoon("ControlEscape")` in init.lua also generates an error.

Can you suggest what to do next?

* Hammerspoon 0.9.55 is installed.
* osMac Sierra 10.12.6

**Comment by jasonrudolph** [comment]
```
...
==> Installing Cask hammerspoon
Error: It seems there is already an App at '/Applications/Hammerspoon.app'.
Error: Install incomplete.
Installing hammerspoon has failed!
Homebrew Bundle failed! 1 Brewfile dependencies failed to install.
```

I'm guessing that this failure ☝️ is due to Hammerspoon being installed manually (i.e., not installed via homebrew) prior to running `script/setup`. Can you try dragging `/Applications/Hammerspoon.app` to the trash and re-running `script/setup`?

---

Note: Ideally, `script/setup` would gracefully handle the scenario where Hammerspoon has already been manually installed. Instead of aborting the setup process, it should just keep going. If anyone knows of a way to tell homebrew to _try_ to install the [Hammerspoon cask](https://github.com/jasonrudolph/ControlEscape.spoon/blob/1f66deee41aaf0f0c0e38aabc0d66977ec8ffedc/Brewfile#L3), but keep going if Hammerspoon is already installed, I'm all ears. 😅

**Comment by spring-haru** [comment]
Thanks. I followed your instruction, and installation finished without problem with a message in Terminal:

```
brew bundle can't satisfy your Brewfile's dependencies.
Satisfy missing dependencies with `brew bundle install`.
Using caskroom/cask
Installing hammerspoon
Homebrew Bundle complete! 2 Brewfile dependencies now installed.
No matching processes belonging to you were found

Hammerspoon version 0.9.54 or greater required. Actual installed version:
hammerspoon: 0.9.55

Done! Be sure to verify your version of Hammerspoon above. If your version is older than 0.9.54, run 'brew update && script/setup' to install a compatible version.
```

Running `script/setup`, Hammerspoon has been updated to 0.9.56.

Adding `hs.loadSpoon("ControlEscape")` in init.lua does not generate an error.

However, tapping Ctrl alone does not give Escape.
I checked it using MacVim and Karabiner-EventViewer.

**Comment by jasonrudolph** [comment]
Thanks for following up.

> Adding `hs.loadSpoon("ControlEscape")` in init.lua does not generate an error.

If installation succeeded fully, your `~/init.lua` file [should include](https://github.com/jasonrudolph/ControlEscape.spoon/blob/1f66deee41aaf0f0c0e38aabc0d66977ec8ffedc/script/setup#L14) this line:

```lua
hs.loadSpoon('ControlEscape'):start() -- Load Hammerspoon bits from https://github.com/jasonrudolph/ControlEscape.spoon
```

If that line is not in your `~/init.lua` file, please add it and restart Hammerspoon.

If that resolves the issue for you, great! If not, please share the contents of your `~/init.lua` file, and I'll try to help you figure out what's going wrong.

**Comment by spring-haru** [comment]
It worked! Thanks for your help (^_^)

**Comment by jasonrudolph** [comment]
> It worked!

Excellent! Thanks for letting me know. 🍰
