### ISSUE TITLE
submit to main list?

### ISSUE THREAD

**Issue by psifertex** [jasonrudolph/ControlEscape.spoon#5]
Is there a reason ControlEscape isn't available on the main spoon list? 

http://www.hammerspoon.org/Spoons/

I'm setting up hammerspoon for the first time and being able to install/configure everything directly via a [SpoonInstall](https://www.hammerspoon.org/Spoons/SpoonInstall.html) directive is handy.

**Comment by jasonrudolph** [comment]
> I'm setting up hammerspoon for the first time and being able to install/configure everything directly via an  [SpoonInstall](https://www.hammerspoon.org/Spoons/SpoonInstall.html)  directive is handy.

👋 Hi @psifertex: That does indeed sound handy!

> Is there a reason ControlEscape isn't available on the main spoon list?

As far as I can tell, the main spoon list is a [monorepo](https://github.com/Hammerspoon/Spoons) that contains every spoon seen at https://www.hammerspoon.org/Spoons/. So, if I were to move ControlEscape to that monorepo, then I’d receive notifications any time someone opens an issue or pull request for any of the spoons in the repo. That sounds like a pretty noisy experience, when I’d really only want to get notifications for issues or pull requests related to ControlEscape. 

So, for now at least, I like the simplicity I get from having ControlEscape live in this repo. 

It would be cool if there were some kind of spoon registry (similar to npm, maven, or rubygems), where spoon authors could publish their spoons and SpoonInstall could then install those spoons. If such a registry existed, I’d be happy to publish ControlEscape to that registry.

**Comment by psifertex** [comment]
Ouch, that is indeed an obnoxious workflow and makes sense you'd want to avoid it. That explains why I had a hard time finding the original authors of some of the other spoons I had questions about! Hopefully they'll figure out how submodules work eventually. 😉
