### ISSUE TITLE
Not working on Catalina

### ISSUE THREAD

**Issue by chrisalcantara** [jasonrudolph/ControlEscape.spoon#7]
Been using this spoon for a very, very long time and recently updated to Catalina. Now, reinstalling this script, I can't seem to get it working. I've switched Caps Lock to Control in general settings, but the spoon doesn't seem to overwrite Caps Lock. Any advice?

**Comment by jasonrudolph** [comment]
👋 @chrisalcantara: Thanks for opening this issue. I honestly haven't tried to use this in macOS Catalina. I use [jasonrudolph/keyboard](https://github.com/jasonrudolph/keyboard) to provide this repository's functionality, and in that case, Karabiner-Elements provides the [<kbd>caps lock</kbd>/<kbd>control</kbd>/<kbd>escape</kbd> customizations](https://github.com/jasonrudolph/keyboard/tree/17d513f126660120f6b00e016fde7ab58719274b#a-more-useful-caps-lock-key).

Given all the permission changes that Catalina introduced, I wouldn't be surprised if some updates are needed to get this spoon to play nicely with Catalina. If anyone is up for investigating this issue and submitting a pull request, I'll be happy to review it. :bow:

**Comment by chrisalcantara** [comment]
Thanks for the response, @jasonrudolph. I think I found a workaround:
I set `caps lock` to `control` in Karabiner and the Catalina keyboard settings.
That seems to have worked thus far. 

However, I would be open to other alternatives.

**Comment by andreaja** [comment]
FWIW I'm on Catalina and have been using the built-in remapping of caps lock to control with this spoon without problems since upgrading.

**Comment by jasonrudolph** [comment]
I haven't heard any more reports of folks running into this issue, and I've never been able to reproduce it myself, so I'm going to close this out. If anyone runs into this and can share steps for reliably reproducing on a fresh installation of Catalina, we can always re-open. :-)
